config/routes.rb
Lidingoslalom::Application.routes.draw do

  resources :groups do
    resources :practices
    resources :members
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :attendances
  resources :messages

  root to: 'sessions#new'

  match '/signout', to: "sessions#destroy", via: :delete
  match 'sessions', to: "sessions#new"
  match 'groups/:id/actions', to: 'groups#actions'
  match 'groups/:id/export', to: 'groups#export'
  match 'groups/:group_id/register', to: 'practices#regindex'
  match 'groups/:group_id/practices/:practice_id/register', to: 'practices#register'

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :text
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def index
		@messages = Message.order("updated_at DESC")
	end

  def new
    @message = Message.new

    respond_to do |format|
      format.html
      format.json { render json: @message }
    end
  end

  def edit
		@message = Message.find(params[:id])
	end

	def create
		@message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_path, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

	def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to messages_path, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
	end

	def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_path }
      format.json { head :no_content }
    end	end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.haml
= form_for(@message) do |f|
  = f.text_area :text, placeholder: 'Meddelande', style: "height: 100px;"
  = f.submit({data: {theme: 'a', icon: 'arrow-r'}})
  %a{data: {role: 'button', theme: 'r', icon: 'delete', rel: 'back'}}Avbryt

app/views/messages/edit.html.haml
= render 'form'

app/views/messages/index.html.haml
%h3{style: "margin-bottom: 20px;"}Meddelanden
- @messages.each do |message|
  .ui-body.ui-body-e
    %b #{l(message.updated_at, format: "%Y-%m-%d").capitalize}
    %br
    #{message.text.gsub(/\n/, '<br>').html_safe}
    %br
    %br
    %a{href: edit_message_path(message)}Redigera
    |
    =link_to "Ta bort", message_path(message), method: :delete, confirm: "Are you sure?"

%a{href: new_message_path, data: {role: 'button', icon: 'plus'}}Nytt meddelande

app/views/messages/new.html.haml
= render 'form'