config/routes.rb
Lidingoslalom::Application.routes.draw do

  resources :groups do
    resources :practices
    resources :members
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :attendances
  resources :messages

  root to: 'sessions#new'

  match '/signout', to: "sessions#destroy", via: :delete
  match 'sessions', to: "sessions#new"
  match 'groups/:id/actions', to: 'groups#actions'
  match 'groups/:id/export', to: 'groups#export'
  match 'groups/:group_id/register', to: 'practices#regindex'
  match 'groups/:group_id/practices/:practice_id/register', to: 'practices#register'

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :sort_order
  has_many :members
  has_many :practices

  def to_csv
  	cols = "#{name}\n"
  	practices.all(order: "date").each do |p|
  		cols = "#{cols},#{p.date}"
  	end

  	rows = "\n"
  	members.all(order: "name ASC").each do |m|
  		rows = "#{rows}#{m.name}"
  		practices.all(order: "date").each do |p|
  			a = m.attendances.where(practice_id: p.id)
				if a.empty?
					attended = ""
				else
					attended = a.first.attended ? "1" : ""
				end

  			rows = "#{rows},#{attended}"
  		end
  		rows = "#{rows}\n"
  	end
  	"#{cols}#{rows}"

  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :signed_in_user

  def index
    @groups = Group.order("sort_order ASC")
    @messages = Message.order("updated_at DESC")

    respond_to do |format|
      format.html
      format.json { render json: @groups }
    end
  end

  def show
    @group = Group.find(params[:id])

    respond_to do | format |
      format.html
      format.json { render json: @group }
    end
  end

  def new
    @group = Group.new

    respond_to do |format|
      format.html
      format.json { render json: @group }
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  def actions
    @group = Group.find(params[:id])
  end

  def export
    @group = Group.find(params[:id])
    @members = Member.where(group_id: @group.id).order("is_trainer DESC, name ASC")
    @practices = Practice.where(group_id: @group.id).order("date ASC")

    respond_to do |format|
      format.html
      format.csv { render text: @group.to_csv }
      format.xls
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= form_for(@group) do |f|
  - if @group.errors.any?
    %div#error_explanation
      %h2
        = pluralize(@group.errors.count, "error")
        prohibited this group from being saved:
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg

  = f.text_field :name, placeholder: 'Gruppens namn'
  = f.submit({data: {theme: 'a', icon: 'arrow-r'}})
  %a{data: {role: 'button', theme: 'r', icon: 'delete', rel: 'back'}}Avbryt

app/views/groups/_group.html.haml
%li= link_to group.name, "#{group.id}/actions"

app/views/groups/actions.html.haml
- provide(:url, "/groups/#{@group.id}/actions/")
%ul{data: {role: 'listview', inset: 'true'}}
	%li= link_to 'Registrera närvaro', "/groups/#{@group.id}/register", :class => 'refresh-page'
	%li= link_to 'Visa alla träningar', group_practices_path(@group)
	%li= link_to 'Lägg till träning', new_group_practice_path(@group)
	%li= link_to 'Medlemslista', group_members_path(@group)
	- if current_user.admin?
		%li= link_to 'Exportera data', "/groups/#{@group.id}/export.xls", "data-ajax" => "false"

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/export.html.haml
%table
	%tr
		%td
		- @practices.each do |p|
			%td=p.date
	- @members.each do |m|
		%tr
			%td=m.name
			- @practices.each do |p|
				- a = m.attendances.where(practice_id: p.id)
				- if a.empty?
					- attended = ""
				- else
					- attended = a.first.attended ? "1" : ""
				%td=attended

app/views/groups/export.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Grupp <%= @group.name %></Data></Cell>
      </Row>
      <Row>
        <Cell></Cell>
        <Cell></Cell>
        <Cell><Data ss:Type="String">Start kl</Data></Cell>
        <% @practices.all(order: "date").each do |p| %>
        <Cell><Data ss:Type="String"><%= p.starts_at.strftime('%H') %></Data></Cell>
        <% end %>
      </Row>
      <Row>
        <Cell></Cell>
        <Cell></Cell>
        <Cell><Data ss:Type="String">Slut kl</Data></Cell>
        <% @practices.all(order: "date").each do |p| %>
        <Cell><Data ss:Type="String"><%= p.ends_at.strftime('%H') %></Data></Cell>
        <% end %>
      </Row>
      <Row></Row>
      <Row>
        <Cell></Cell>
        <Cell></Cell>
        <Cell><Data ss:Type="String">Månad</Data></Cell>
        <% @practices.all(order: "date").each do |p| %>
        <Cell><Data ss:Type="String"><%= p.date.strftime('%m') %></Data></Cell>
        <% end %>
      </Row>
      <Row>
        <Cell></Cell>
        <Cell></Cell>
        <Cell><Data ss:Type="String">Dag</Data></Cell>
        <% @practices.all(order: "date").each do |p| %>
        <Cell><Data ss:Type="String"><%= p.date.strftime('%d') %></Data></Cell>
        <% end %>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">Medlemsnummer</Data></Cell>
        <Cell><Data ss:Type="String">Namn</Data></Cell>
        <Cell><Data ss:Type="String">Född</Data></Cell>
      </Row>
      <% @members.each do |m| %>
      <Row>
        <Cell><Data ss:Type="String"><%= m.ref_number %></Data></Cell>
        <Cell><Data ss:Type="String"><%= m.name %></Data></Cell>
        <% if m.is_trainer %>
        <Cell><Data ss:Type="String">Tränare</Data></Cell>
        <% else %>
        <Cell><Data ss:Type="String"><%= m.birthyear.strftime('%y') %></Data></Cell>
        <% end %>
        <%  @practices.all(order: "date").each do |p|
              a = m.attendances.where(practice_id: p.id)
              if a.empty?
                attended = ""
              else
                attended = a.first.attended ? "1" : ""
              end
              if attended == "1"
        %>
          <Cell><Data ss:Type="Number"><%= attended %></Data></Cell>
        <%    else %>
          <Cell><Data ss:Type="String"></Data></Cell>
        <%    end
            end %>
      </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/groups/index.html.haml
- provide(:url, '/groups/')
%h2 Välj träningsgrupp
%ul{data: {role: 'listview', inset: 'true'}}
	= render @groups
- if current_user.admin?
	%a{href: new_group_path, data: {role: 'button', icon: 'plus'}}Lägg till grupp

%h2{style: "margin-top: 30px;"} Meddelanden från medlemsansvarig / styrelse
- @messages.each do |m|
	.ui-body.ui-body-e
		%b #{l(m.updated_at, format: "%Y-%m-%d").capitalize}
		%br
		= m.text.gsub(/\n/, '<br>').html_safe

- if current_user.admin?
	%a{href: messages_path, data: {role: 'button'}}Hantera meddelanden


%div{style: "margin-top:20px;"}
	=button_to "Logga ut", signout_path, method: :delete, data: {role: 'button', theme: 'r'}

app/views/groups/new.html.haml
- provide(:url, '/groups/')
%h2 Skapa ny grupp
= render 'form'

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>